### PR TITLE
Deployment Test

### PR DESCRIPTION
**Pull request by sleephu**
This PR is to make the project be ready for deployment by using jetty and it can be deployed locally already.
To-do: Deploy to heroku.

Usage: 
    In order to run the web app, need to get web framework supported.

    To run the web app:
    1. Go to /src/main/Main.java
    2. Run it (as plain java class)

  Some major changes:

     1. Move web folder to /src/main/ folder, and rename it to webapp, so its path is /src/main/webapp
        some corresponding setting changed is the web resource directory path configuration in Project Structure - Facets:

   screen shot 2016-07-21 at 5 12 04 pm

     2. Pom.xml
         a. Add jetty maven plugin (see <!-heroku deployment-!>)
         b. Add jetty runner dependency

     3. Main.java (/src/main/Main.java)
         It is the configuration class for jetty working.

     4. Procfile file
         It is configuration file for heroku deployment.
         FYI: https://devcenter.heroku.com/articles/procfile#deploying-to-heroku

Some fix:

      1. AdsDaoTest.java (fixed)
         The campaign test was failed because of the unexpected value for expected value.

      2. AdsSelectionTest.java (To-do)
         Test failed and haven't figure out the reason yet.

@lijljacklee @dojiangv 

FYI: Configuration for web application in Intellij.

Steps:
   1. Download ultimate version for Intellij.

   2. Right click the project to select "Add Framework Support", and choose web framework.

   3. Go to Project Structure to do some configurations:
       a. Artifacts:

   screen shot 2016-07-21 at 5 05 28 pm

       b. Facets:

  screen shot 2016-07-21 at 5 12 04 pm

### CODE REVIEW

**Comment by sleephu** [comment]
This branch has conflicts because I changed a lot of structure things. You guys could download to see whether it works locally(remember to set your own path in AdsDao for the data files).

**Comment by lijljacklee** [comment]
LGTM 👍 Thx Jackie! Your branch helps.

**Comment by lijljacklee** [comment]
@sleephu It seems the `AdsSelectionTest` has passed. Cannot regenerate the issue you mentioned.

**Comment by sleephu** [comment]
Need to fix file path in AdsEngine.

**Pull request merged**
